# Generated by Django 4.1.7 on 2023-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezradjango_dtbregistration', '0002_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, default=750129885, max_length=50),
            preserve_default=False,
        ),
    ]
